apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: maria # example
spec:
  # This is an encoded CSR. Change this to the base64-encoded contents of myuser.csr
  groups:
  - system:authenticated
  request: ${BASE64_CSR}
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
