loki:
  auth_enabled: false
  # Use this instead of `config`
  server:
    grpc_server_max_recv_msg_size: 20971520
    grpc_server_max_send_msg_size: 20971520
  
  config:
    memberlist:
      cluster_label: "loki"
    schema_config:
      configs:
        - from: "2019-07-14"
          store: tsdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
        - from: "2023-07-20"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    limits_config:
      retention_period: 24h
      ingestion_rate_mb: 4
      ingestion_burst_size_mb: 6
    storage_config:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    compactor:
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    ingester:
      autoforget_unhealthy: true
    common:
      replication_factor: 1
      storage:
        bucketNames:
          chunks: chunks
          ruler: ruler
          admin: admin

resultsCache:
  enabled: false
chunksCache:
  enabled: false

write:
  replicas: 1
  autoscaling:
    enabled: false
  extraArgs:
    - "-log.level=info"
  maxUnavailable: 0
      
read:
  replicas: 1
  autoscaling:
    enabled: false
  extraArgs:
    - "-log.level=info"
  maxUnavailable: 0

backend:
  replicas: 1
  autoscaling:
    enabled: false
  extraArgs:
    - "-log.level=info"
  maxUnavailable: 0

lokiCanary:
  enabled: false

sidecar:
  rules:
    enabled: false

serviceMonitor:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false

test:
  enabled: false

enterprise:
  enabled: false

gateway:
  enabled: false
