#cloud-config
package_update: true
packages:
- nginx
- curl
write_files:
  - path: /var/www/html/index.html
    content: |
      <html>
      <body>
        <h1>Hello, from Nazar!</h1>
        <p>Welcome to the example web page!</p>
      </body>
      </html>
    owner: 'root:root'
    permissions: '0644'
runcmd:
- [systemctl, enable, nginx]
- [systemctl, start, nginx]
