apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  namespace: default
  labels:
    release: prometheus  # Match your Prometheus Operator's label selector
    team: devops
    app: nginx-exporter
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
