{
 "title": "Web Analytics Dashboard (for onboarding)",
 "description": "A version of the NGINX dashboard, specific to the onboarding training exercise",
 "time": { "from": "2025-04-13T19:05:41.500Z", "to": "2025-04-13T20:22:58.033Z" },
 "panels": [
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (code) (count_over_time({level=\"access\"} | regexp \"HTTP/1.1\\\" (?P<code>\\\\d{3}) \"[$__interval]))"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({level=\"access\"} | logfmt [1h])"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (\n  rate(\n    {level=\"access\"}\n    | logfmt\n    | size > 0\n    | unwrap size\n    [$__interval]\n  )\n)"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (code) (count_over_time({level=\"access\"} | regexp \"HTTP/1.1\\\" (?P<code>\\\\d{3}) \"[$__interval]))"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by (client_ip) (count_over_time({level=\"access\"} | regexp \"(?P<client_ip>\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3})\"[$__interval])))"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, count by(path) (rate({level=\"access\"} [1m])))"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (agent) (count_over_time({level=\"access\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{level=\"access\"}"
    }
   ]
  }
 ]
}