apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit1
  namespace: default
  labels:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "fluentbit"
  annotations:
    meta.helm.sh/release-name: "fluentbit"
    meta.helm.sh/release-namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - pods/logs
  - events
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit1
  namespace: default
