{{- if .Values.fluentbit.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fluentbit.name }}-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - pods/logs
  - events
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.fluentbit.name }}-read
subjects:
- kind: ServiceAccount
  name: {{ include "kube-observability.fluentbit.fullname" . }}
  namespace: {{ .Values.fluentbit.namespace | default .Release.Namespace }}

{{ end }}