{{ if .Values.fluentbit.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-observability.fluentbit.fullname" . }}
  namespace: {{ .Values.fluentbit.namespace | default .Release.Namespace }}
{{- end }}
